// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: auth.proto

package server

import (
	"context"

	"api/v1/auth"
	"auth/internal/logic"
	"auth/internal/svc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	auth.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) Ping(ctx context.Context, in *auth.PingReq) (*auth.PingResp, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
