// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package handler

import (
	"net/http"

	auth "github.com/uwu-octane/antBackend/gateway/internal/handler/auth"
	"github.com/uwu-octane/antBackend/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
		{
			Method:  http.MethodPost,
			Path:    "/login",
			Handler: auth.LoginHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/me",
			Handler: auth.MeHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/ping",
			Handler: auth.PingHandler(serverCtx),
		},
		{
			Method:  http.MethodPost,
			Path:    "/refresh",
			Handler: auth.RefreshHandler(serverCtx),
		},
		{
			Method:  http.MethodGet,
			Path:    "/user/info",
			Handler: auth.GetUserInfoHandler(serverCtx),
		},
		},
		rest.WithPrefix("/api/v1"),
	)
}
