// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type Request struct {
	LoginRequest struct {
		Username string `json:"username"`
		Password string `json:"password"`
	}
}

type Response struct {
	LoginResponse struct {
		AccessToken  string `json:"access_token"`
		RefreshToken string `json:"refresh_token"`
		ExpiresIn    int64  `json:"expires_in"`
	}
	UserInfoResponse struct {
		UserId   int64  `json:"user_id"`
		Username string `json:"username"`
		Email    string `json:"email"`
	}
}
