// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1

package types

type EmptyResp struct {
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResp struct {
	AccessToken string `json:"access_token"`
	SessionId   string `json:"session_id"`
	ExpiresIn   int64  `json:"expires_in"`
	TokenType   string `json:"token_type"`
}

type LogoutResp struct {
	Ok      bool   `json:"ok"`
	Message string `json:"message"`
}

type MeResp struct {
	Uid string `json:"uid"`
	Jti string `json:"jti"`
	Iat int64  `json:"iat"`
}

type UserInfoResp struct {
	UserId      string `json:"user_id"`
	Username    string `json:"username"`
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	AvatarUrl   string `json:"avatar_url"`
}
