// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.1
// Source: auth.proto

package authservice

import (
	"context"

	"github.com/uwu-octane/antBackend/api/v1/auth"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PingReq  = auth.PingReq
	PingResp = auth.PingResp

	AuthService interface {
		Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error)
	}

	defaultAuthService struct {
		cli zrpc.Client
	}
)

func NewAuthService(cli zrpc.Client) AuthService {
	return &defaultAuthService{
		cli: cli,
	}
}

func (m *defaultAuthService) Ping(ctx context.Context, in *PingReq, opts ...grpc.CallOption) (*PingResp, error) {
	client := auth.NewAuthServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
